[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
rpc_endpoints = { sepolia = "https://ethereum-sepolia.rpc.subquery.network/public", arb-sepolia = "https://endpoints.omniatech.io/v1/arbitrum/sepolia/public"}
remappings = [
    "@openzeppelin/contracts@4.8.3/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts@5.0.2/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@ccip/=lib/ccip/",
    "@chainlink/local/=lib/chainlink-local/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
